"""add vol

Revision ID: 72cecc47c415
Revises: bb1c14ca803f
Create Date: 2025-10-30 10:58:42.812933

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72cecc47c415'
down_revision: Union[str, Sequence[str], None] = 'bb1c14ca803f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apple', sa.Column('vol', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apple', 'vol')
    # ### end Alembic commands ###
